---
name: conntest
namespace: conntest
replicas: 3

cloud: aws
cloudConfig:
  aws:
    sslCertificateArn: arn:aws:acm:us-east-1:914373874199:certificate/a7124cf8-7719-449a-83d5-2fa3c72ea1f3
    useProxyProtocol: false
    listenPort: 443

containers:
  - dockerfile: Dockerfile
    context: .
    rebuild:
      root: /srv
      command: ./gradlew test fatJar
      sources:
        - build.gradle
        - settings.gradle
        - gradle.properties
        - gradlew
        - src

profiles:
  dev:
    name: {{ branch.replace('/', '-') }}
  staging:
    name: next
  stable:
    name: stable

branches:
  master: stable
  dev/*:  dev