---
{%- if service.cloud is defined and service.cloud == "aws" %}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    {%- if service.cloudConfig.aws.sslCertificateArn %}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ service.cloudConfig.aws.sslCertificateArn }}
    {% endif %}
    {% if service.cloudConfig.aws.useProxyProtocol == true %}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    {% endif %}
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: {{ service.cloudConfig.aws.listenPort }}
    targetPort: 80
  selector:
    service: ambassador
{% else %}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
spec:
  type: NodePort
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
{% endif -%}
