---
apiVersion: v1
kind: Service
metadata:
  name: conntest-{{ build.profile.name }}-nodeport
  namespace: {{ service.namespace }}
  labels:
    app: conntest-nodeport
spec:
  selector:
    app: conntest-{{ build.profile.name }}
  type: NodePort
  ports:
    - name: http-api
      port: 80
      protocol: TCP
      targetPort: http-api
  externalTrafficPolicy: Local

---
apiVersion: v1
kind: Service
metadata:
  name: conntest-{{ build.profile.name }}
  namespace: {{ service.namespace }}
  labels:
    app: conntest
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  ambassador
      config:
      {%- if service.cloud == "aws" and service.cloudConfig.aws.useProxyProtocol == true %}
        use_proxy_proto: true
      {% else %}
        use_proxy_proto: false
      {% endif %}

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: conntest-{{ build.profile.name }}
      prefix: /
      host: conntest-{{ build.profile.name }}.kubernaut.io
      service: conntest-{{ build.profile.name }}.{{ service.namespace }}:7000

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: conntest-{{ build.profile.name }}-websocket
      prefix: /ws
      rewrite: /ws
      use_websocket: true
      host: conntest-{{ build.profile.name }}.kubernaut.io
      service: conntest-{{ build.profile.name }}.{{ service.namespace }}:7000
spec:
  selector:
    app: conntest-{{ build.profile.name }}
  type: {{ build.profile.service_type | default("ClusterIP") }}
  ports:
    - name: http-api
      port: 7000
      protocol: TCP
      targetPort: http-api

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conntest-{{ build.profile.name }}
  namespace: {{ service.namespace }}
  labels:
    app: conntest-{{ build.profile.name }}
spec:
  replicas: {{ service.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: conntest-{{ build.profile.name }}
    spec:
      containers:
        - name: conntest
          image: {{ build.images["Dockerfile"] }}
          ports:
            - name: http-api
              containerPort: 7000
